using System;
using System.Collections.Generic;
using ApplicationLayer.DTOs.Transfers;
using DomainLayer.Enums;

namespace ApplicationLayer.DTOs.BranchRequests
{
    // =====================================================================================
    //  Requests
    // =====================================================================================

    /// <summary>One requested product line on a new stock request.</summary>
    /// <param name="ProductId">Product being requested.</param>
    /// <param name="AskedQuantity">How many are needed. Must be greater than zero.</param>
    public sealed record StockRequestLine(long ProductId, int AskedQuantity);

    /// <summary>
    /// Payload for <c>POST /api/inventory/requests</c> (API §4.9). Raises a branch's recorded
    /// need for stock. Reserves nothing and moves no stock — see
    /// <c>BranchRequestErrors.DuplicateOpenRequest</c> for the one guard against redundant
    /// requests (decision Q-11 / D-08).
    /// </summary>
    /// <param name="RequestingBranchId">
    /// The branch asking for stock. Caller-asserted (decision note §11: the JWT carries no
    /// branch claim), validated as tenant-owned, not deleted, and active (decision Q-13).
    /// </param>
    /// <param name="Items">Requested product lines. At least one, with no repeated product.</param>
    /// <param name="ActionNotes">Optional free-text note stored on the request.</param>
    public sealed record CreateStockRequest(
        long RequestingBranchId,
        IReadOnlyList<StockRequestLine> Items,
        string? ActionNotes = null);

    /// <summary>
    /// One transfer to be generated by a confirm call. Source is specified per transfer, not per
    /// line (decision Q-14) — a single product split across two sources becomes two transfers.
    /// <para>
    /// <see cref="Items"/> deliberately reuses <see cref="CreateTransferLine"/> rather than
    /// <see cref="StockRequestLine"/>: the shipped <c>TransferService</c>/<c>ITransferComposer</c>
    /// requires explicit <c>ProductItemIds</c> for a Known-way line at create time, so the
    /// confirm payload has to carry the same shape a direct transfer create does — the API
    /// specification's <c>items[{productId, transactedQuantity}]</c> is insufficient on its own.
    /// </para>
    /// </summary>
    /// <param name="SourceBranchId">
    /// Branch the cards leave. Must differ from the request's requesting branch
    /// (<c>BranchRequestErrors.SourceIsRequestingBranch</c>) — pre-empts the database check that
    /// would otherwise fire when the generated transfer is staged.
    /// </param>
    /// <param name="Items">
    /// Product lines for this transfer. Over-fulfilment is allowed (decision Q-03): a line's
    /// quantity may exceed what was asked, and a product absent from the request may appear here
    /// (see decision D-05 on how such lines are — and are not — recorded against the request).
    /// </param>
    /// <param name="ActionNotes">Optional free-text note stored on the generated transfer.</param>
    public sealed record ConfirmTransferPlan(
        long SourceBranchId,
        IReadOnlyList<CreateTransferLine> Items,
        string? ActionNotes = null);

    /// <summary>
    /// Payload for <c>POST /api/inventory/requests/{id}/confirm</c> (API §4.9). Generates one or
    /// more transfers in a single transaction — either every plan validates and every transfer is
    /// staged, or nothing is (decision Q-06 removed any cap on how many). Callable repeatedly
    /// against the same request (decision Q-04, incremental fulfilment) from any non-terminal
    /// status.
    /// </summary>
    /// <param name="Transfers">One or more transfer plans. At least one.</param>
    /// <param name="ActionNotes">
    /// Optional free-text note stored on the request itself (distinct from each plan's own
    /// <see cref="ConfirmTransferPlan.ActionNotes"/>, which lands on its generated transfer).
    /// </param>
    public sealed record ConfirmStockRequest(
        IReadOnlyList<ConfirmTransferPlan> Transfers,
        string? ActionNotes = null);

    /// <summary>
    /// Payload for <c>POST /api/inventory/requests/{id}/refuse</c> (API §4.9). Closes the request
    /// without generating anything.
    /// </summary>
    /// <param name="ActionNotes">
    /// Reason for the refusal. Optional (decision Q-10) — the API specification's mandatory
    /// reason is deliberately relaxed to match the shipped auth model, where the refuser and the
    /// requester are necessarily the same tenant account.
    /// </param>
    public sealed record RefuseStockRequest(string? ActionNotes = null);

    /// <summary>
    /// Payload for <c>POST /api/inventory/requests/{id}/cancel</c> (API §4.9). Closes the
    /// request without generating anything, from the requester's side.
    /// </summary>
    /// <param name="ActionNotes">Optional free-text note.</param>
    public sealed record CancelStockRequest(string? ActionNotes = null);

    // =====================================================================================
    //  Responses
    // =====================================================================================

    /// <summary>One requested product line as returned by the request detail endpoint.</summary>
    /// <param name="AskedQuantity">Quantity originally requested.</param>
    /// <param name="DispatchedQuantity">
    /// Cumulative quantity dispatched across every transfer this request has generated for this
    /// product (decision D-01). Never decremented by a later return or disposal.
    /// </param>
    /// <param name="ReceivedQuantity">
    /// Cumulative quantity actually credited to the requesting branch — the fulfilment measure
    /// that drives the request's status (decision D-01, D-03).
    /// </param>
    /// <param name="OutstandingQuantity">
    /// Derived as <c>max(0, AskedQuantity - ReceivedQuantity)</c>. Not stored: over-fulfilment
    /// (decision Q-03) means <see cref="ReceivedQuantity"/> can exceed
    /// <see cref="AskedQuantity"/>, and this must never go negative.
    /// </param>
    /// <param name="ProductTransactionWay">
    /// Snapshotted at read time from the live product — unlike <c>CardTransferProduct</c>, a
    /// request line carries no way of its own to snapshot, since it names a demand rather than a
    /// dispatched shipment. Included so a client can anticipate whether a future confirm's
    /// generated transfer will need explicit card ids.
    /// </param>
    public sealed record StockRequestItemResponse(
        long ProductId,
        string ProductName,
        int AskedQuantity,
        int DispatchedQuantity,
        int ReceivedQuantity,
        int OutstandingQuantity,
        ProductTransactionWay ProductTransactionWay);

    /// <summary>
    /// A product dispatched under this request that was never asked for (decision D-05). Confirm
    /// may name products outside the request's own lines (decision Q-03); since a
    /// <c>BranchRequestItem</c> cannot represent one (its <c>AskedQuantity &gt; 0</c> check would
    /// fail), these are surfaced instead as a read-only collection derived from the request's
    /// linked transfers.
    /// </summary>
    public sealed record UnrequestedProductResponse(
        long ProductId,
        string ProductName,
        int DispatchedQuantity,
        int ReceivedQuantity);

    /// <summary>Row shape for <c>GET /api/inventory/requests</c>.</summary>
    public sealed record StockRequestListItemResponse(
        long Id,
        long TenantId,
        long RequestingBranchId,
        string RequestingBranchName,
        BranchRequestStatus RequestStatus,
        int LineCount,
        int TotalAskedQuantity,
        int TotalReceivedQuantity,
        DateTime RequestDateTime,
        DateTime? ActionTakenAt);

    /// <summary>
    /// Full request detail as returned by <c>GET /api/inventory/requests/{id}</c> and, wrapped in
    /// <see cref="ConfirmStockRequestResult"/>, by a successful confirm.
    /// </summary>
    /// <param name="RowVersion">Base64-encoded optimistic-concurrency token (decision Q-07).</param>
    /// <param name="Items">The request's own lines, each with its fulfilment counters.</param>
    /// <param name="UnrequestedProducts">Products dispatched but never asked for (decision D-05).</param>
    /// <param name="TransferIds">
    /// Every transfer this request has generated, in creation order — including auto-generated
    /// returns, which inherit this request's id (decision D-04). Full detail is available via
    /// <c>GET /api/inventory/transactions?branchRequestId={id}</c>, already wired.
    /// </param>
    public sealed record StockRequestDetailResponse(
        long Id,
        long TenantId,
        long RequestingBranchId,
        string RequestingBranchName,
        BranchRequestStatus RequestStatus,
        DateTime RequestDateTime,
        long? ActionTakenByTenantId,
        DateTime? ActionTakenAt,
        string? ActionNotes,
        string RowVersion,
        IReadOnlyList<StockRequestItemResponse> Items,
        IReadOnlyList<UnrequestedProductResponse> UnrequestedProducts,
        IReadOnlyList<long> TransferIds);

    /// <summary>
    /// Outcome of a successful confirm. Carries full transfer details, not just ids (decision
    /// Q-12), so the caller does not have to make a second round trip to see what was generated.
    /// </summary>
    public sealed record ConfirmStockRequestResult(
        StockRequestDetailResponse Request,
        IReadOnlyList<TransferDetailResponse> Transfers);

    // =====================================================================================
    //  Filters
    // =====================================================================================

    /// <summary>
    /// Filter and paging inputs for <c>GET /api/inventory/requests</c> (API §3.1, §4.9). Bound
    /// from the query string.
    /// </summary>
    /// <param name="Status">Optional lifecycle filter.</param>
    /// <param name="RequestingBranchId">Optional filter on the requesting branch.</param>
    /// <param name="ProductId">Optional filter on a product appearing on a request line.</param>
    /// <param name="FromDate">Inclusive lower bound on <c>RequestDateTime</c> (UTC).</param>
    /// <param name="ToDate">Inclusive upper bound on <c>RequestDateTime</c> (UTC).</param>
    /// <param name="TenantId">System-admin-only tenant filter; ignored for tenant callers.</param>
    /// <param name="Page">1-based page index. Defaults to 1.</param>
    /// <param name="PageSize">Items per page (max 100). Defaults to 20.</param>
    /// <param name="SortBy">requestdatetime (default) | status | requestingbranchid.</param>
    /// <param name="SortDir">
    /// asc or desc. Defaults to <c>desc</c> — newest first, matching
    /// <see cref="ApplicationLayer.DTOs.Transfers.TransferListFilter"/>.
    /// </param>
    public sealed record StockRequestListFilter(
        BranchRequestStatus? Status = null,
        long? RequestingBranchId = null,
        long? ProductId = null,
        DateTime? FromDate = null,
        DateTime? ToDate = null,
        long? TenantId = null,
        int Page = 1,
        int PageSize = 20,
        string? SortBy = null,
        string? SortDir = "desc");
}
