namespace DomainLayer.Enums
{
    /// <summary>
    /// Whether a transfer was raised by a person or manufactured by the system (API §4.10,
    /// decision Q5). Persisted as <c>TINYINT</c>.
    /// <para>
    /// The distinction is not cosmetic: an auto-generated return exists only because a person
    /// declined part of a shipment, so reporting that counts "transfers created" would double-count
    /// the same operational event without this flag, and a UI that lists returns alongside
    /// outbound shipments would read as noise.
    /// </para>
    /// <para>
    /// <b>Schema note:</b> not in the ERD; added with decision Q5 (approved).
    /// </para>
    /// </summary>
    public enum TransactionOrigin : byte
    {
        /// <summary>Raised directly by a tenant user, or (later) by confirming a branch request.</summary>
        UserCreated = 0,

        /// <summary>
        /// Manufactured by the system to carry the unreceived remainder of a partially received
        /// transfer back to its source. Follows the ordinary lifecycle: the source branch must
        /// explicitly receive or dispose it.
        /// </summary>
        AutoGeneratedReturn = 1
    }
}
