// <auto-generated />
using System;
using InfrastructureLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfrastructureLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823064304_Add-Migration Matica-Print-Flow-Tipper-Parameters")]
    partial class AddMigrationMaticaPrintFlowTipperParameters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ActorTenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActorTenantId", "Timestamp");

                    b.HasIndex("EntityName", "EntityId");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.Batch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<int>("BatchCardAmount")
                        .HasColumnType("int");

                    b.Property<int>("BatchStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FileMac")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProcessedRowCount")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UploadedByTenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("BatchStatus")
                        .HasDatabaseName("IX_batch_status");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_batch_name");

                    b.HasIndex("UploadedByTenantId", "FileMac")
                        .IsUnique()
                        .HasDatabaseName("IX_Batches_UploadedByTenantId_FileMac")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UploadedByTenantId", "UploadedTime")
                        .HasDatabaseName("IX_Batches_UploadedByTenantId_UploadedTime");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("DomainLayer.Entities.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Category_Name");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Branch_TenantId_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.BranchRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ActionTakenAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ActionTakenByTenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("RequestStatus")
                        .HasColumnType("tinyint");

                    b.Property<long>("RequestingBranchId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActionTakenByTenantId");

                    b.HasIndex("RequestingBranchId");

                    b.HasIndex("TenantId", "RequestDateTime")
                        .HasDatabaseName("IX_BranchRequests_TenantId_RequestDateTime");

                    b.HasIndex("TenantId", "RequestStatus")
                        .HasDatabaseName("IX_BranchRequests_TenantId_RequestStatus");

                    b.HasIndex("TenantId", "RequestingBranchId")
                        .HasDatabaseName("IX_BranchRequests_TenantId_RequestingBranchId");

                    b.ToTable("BranchRequests", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.BranchRequestItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AskedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("DispatchedQuantity")
                        .HasColumnType("int");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("int");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_BranchRequestItems_RequestId_ProductId");

                    b.HasIndex("TenantId", "RequestId")
                        .HasDatabaseName("IX_BranchRequestItems_TenantId_RequestId");

                    b.ToTable("BranchRequestItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_BranchRequestItems_AskedQuantity_Positive", "[AskedQuantity] > 0");

                            t.HasCheckConstraint("CK_BranchRequestItems_DispatchedQuantity_NonNegative", "[DispatchedQuantity] >= 0");

                            t.HasCheckConstraint("CK_BranchRequestItems_ReceivedQuantity_NonNegative", "[ReceivedQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.CardDisposal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CardTransferId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DisposedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DisposedByTenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CardTransferId")
                        .HasDatabaseName("IX_CardDisposals_CardTransferId");

                    b.HasIndex("DisposedByTenantId");

                    b.HasIndex("TenantId", "BranchId")
                        .HasDatabaseName("IX_CardDisposals_TenantId_BranchId");

                    b.HasIndex("TenantId", "DisposedAt")
                        .HasDatabaseName("IX_CardDisposals_TenantId_DisposedAt");

                    b.ToTable("CardDisposals", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.CardDisposalItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CardDisposalId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId");

                    b.HasIndex("CardDisposalId", "ProductItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_CardDisposalItems_CardDisposalId_ProductItemId");

                    b.HasIndex("TenantId", "CardDisposalId")
                        .HasDatabaseName("IX_CardDisposalItems_TenantId_CardDisposalId");

                    b.ToTable("CardDisposalItems", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.CardTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("BranchRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("CheckedByUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByTenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("unknown");

                    b.Property<byte>("Origin")
                        .HasColumnType("tinyint");

                    b.Property<long?>("ParentTransferId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceBranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("TargetBranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<byte>("TransactionStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BranchRequestId");

                    b.HasIndex("CreatedByTenantId");

                    b.HasIndex("ParentTransferId")
                        .HasDatabaseName("IX_CardsTransferHistory_ParentTransferId");

                    b.HasIndex("SourceBranchId")
                        .HasDatabaseName("IX_CardsTransferHistory_SourceBranchId");

                    b.HasIndex("TargetBranchId")
                        .HasDatabaseName("IX_CardsTransferHistory_TargetBranchId");

                    b.HasIndex("TenantId", "BranchRequestId")
                        .HasDatabaseName("IX_CardsTransferHistory_TenantId_BranchRequestId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_CardsTransferHistory_TenantId_CreatedAt");

                    b.HasIndex("TenantId", "Origin")
                        .HasDatabaseName("IX_CardsTransferHistory_TenantId_Origin");

                    b.HasIndex("TenantId", "TransactionStatus")
                        .HasDatabaseName("IX_CardsTransferHistory_TenantId_TransactionStatus");

                    b.ToTable("CardsTransferHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_CardsTransferHistory_SourceNotTarget", "[SourceBranchId] <> [TargetBranchId]");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.CardTransferItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CardTransferId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductItemId")
                        .HasColumnType("bigint");

                    b.Property<byte>("ReceiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId")
                        .HasDatabaseName("IX_CardTransferItems_ProductItemId");

                    b.HasIndex("CardTransferId", "ProductItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_CardTransferItems_CardTransferId_ProductItemId");

                    b.HasIndex("TenantId", "CardTransferId")
                        .HasDatabaseName("IX_CardTransferItems_TenantId_CardTransferId");

                    b.ToTable("CardTransferItems", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.CardTransferProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CardTransferId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("DifferenceAction")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DisposedQuantity")
                        .HasColumnType("int");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<byte>("ProductTransactionWay")
                        .HasColumnType("tinyint");

                    b.Property<int?>("RealQuantityReceived")
                        .HasColumnType("int");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactedQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CardTransferId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_CardTransferProducts_CardTransferId_ProductId");

                    b.HasIndex("TenantId", "CardTransferId")
                        .HasDatabaseName("IX_CardTransferProducts_TenantId_CardTransferId");

                    b.ToTable("CardTransferProducts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CardTransferProducts_DisposedQuantity_NonNegative", "[DisposedQuantity] IS NULL OR [DisposedQuantity] >= 0");

                            t.HasCheckConstraint("CK_CardTransferProducts_RealQuantityReceived_NonNegative", "[RealQuantityReceived] IS NULL OR [RealQuantityReceived] >= 0");

                            t.HasCheckConstraint("CK_CardTransferProducts_SettlementWithinTransacted", "ISNULL([RealQuantityReceived], 0) + ISNULL([DisposedQuantity], 0) <= [TransactedQuantity]");

                            t.HasCheckConstraint("CK_CardTransferProducts_TransactedQuantity_Positive", "[TransactedQuantity] > 0");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.EvolisProductPrintConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ImageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PrintColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<byte>("PrintWay")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PrintedFace")
                        .HasColumnType("tinyint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("RibbonTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("IX_EvolisProductPrintConfigurations_ImageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RibbonTypeId")
                        .HasDatabaseName("IX_EvolisProductPrintConfigurations_RibbonTypeId");

                    b.HasIndex("TenantId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_EvolisProductPrintConfigurations_TenantId_ProductId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("EvolisProductPrintConfigurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvolisProductPrintConfigurations_FontSize_NonNegative", "[FontSize] >= 0");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.MaticaPrinterConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("FeederId")
                        .HasColumnType("int");

                    b.Property<int>("HopperId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PrinterId")
                        .HasColumnType("bigint");

                    b.Property<int>("RejectedId")
                        .HasColumnType("int");

                    b.Property<int>("TipperConsumption")
                        .HasColumnType("int");

                    b.Property<int>("TipperPressure")
                        .HasColumnType("int");

                    b.Property<int>("TipperTemperature")
                        .HasColumnType("int");

                    b.Property<int>("TipperTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId")
                        .IsUnique()
                        .HasDatabaseName("UX_MaticaPrinterConfigurations_PrinterId");

                    b.ToTable("MaticaPrinterConfigurations", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.MaticaProductPrintConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cpi")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<long?>("ImageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OffsetX")
                        .HasColumnType("int");

                    b.Property<int>("OffsetY")
                        .HasColumnType("int");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("IX_MaticaProductPrintConfigurations_ImageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_MaticaProductPrintConfigurations_TenantId_ProductId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("MaticaProductPrintConfigurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaticaProductPrintConfigurations_FontSize_NonNegative", "[FontSize] >= 0");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.PrintImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OriginalFileName")
                        .IsUnique()
                        .HasDatabaseName("UX_PrintImages_TenantId_OriginalFileName");

                    b.ToTable("PrintImages", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.Printer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("UsingPrinterType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("TenantId", "BranchId")
                        .HasDatabaseName("IX_Printers_TenantId_BranchId");

                    b.HasIndex("TenantId", "UniqueNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Printers_TenantId_UniqueNumber")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "UsingPrinterType")
                        .HasDatabaseName("IX_Printers_TenantId_UsingPrinterType");

                    b.ToTable("Printers", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("ActivationStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LowProductThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("ProductTransactionWay")
                        .HasColumnType("tinyint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("UsingPrinterType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Product_TenantId_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.ProductItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BranchID")
                        .HasColumnType("bigint");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PanFingerprint")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BatchId");

                    b.HasIndex("BranchID");

                    b.HasIndex("CardHolderName")
                        .HasDatabaseName("IX_card_holder_name");

                    b.HasIndex("ProductId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_card_status_name");

                    b.HasIndex("TenantId", "PanFingerprint")
                        .IsUnique()
                        .HasDatabaseName("IX_Cards_TenantId_PanFingerprint")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "BranchID", "Status")
                        .HasDatabaseName("IX_Cards_TenantId_BranchId_Status");

                    b.HasIndex("TenantId", "ProductId", "BranchID", "PanFingerprint")
                        .HasDatabaseName("IX_Cards_TenantId_ProductId_BranchId_PanFingerprint");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DomainLayer.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("userName");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.RibbonType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_RibbonTypes_Name");

                    b.ToTable("RibbonTypes", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.Stock", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("HoldQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TenantId", "BranchId", "ProductId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("IX_Stocks_TenantId_ProductId");

                    b.ToTable("Stocks", t =>
                        {
                            t.HasCheckConstraint("CK_Stocks_AvailableQuantity_NonNegative", "[AvailableQuantity] >= 0");

                            t.HasCheckConstraint("CK_Stocks_HoldQuantity_NonNegative", "[HoldQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.SystemAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SystemAdmins", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Entities.Batch", b =>
                {
                    b.HasOne("DomainLayer.Entities.Tenant", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("UploadedByTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DomainLayer.Entities.Branch", b =>
                {
                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainLayer.Entities.BranchRequest", b =>
                {
                    b.HasOne("DomainLayer.Entities.Tenant", "ActionTakenByTenant")
                        .WithMany()
                        .HasForeignKey("ActionTakenByTenantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Entities.Branch", "RequestingBranch")
                        .WithMany()
                        .HasForeignKey("RequestingBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActionTakenByTenant");

                    b.Navigation("RequestingBranch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DomainLayer.Entities.BranchRequestItem", b =>
                {
                    b.HasOne("DomainLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.BranchRequest", "Request")
                        .WithMany("Items")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("DomainLayer.Entities.CardDisposal", b =>
                {
                    b.HasOne("DomainLayer.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.CardTransfer", "CardTransfer")
                        .WithMany()
                        .HasForeignKey("CardTransferId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Entities.Tenant", "DisposedByTenant")
                        .WithMany()
                        .HasForeignKey("DisposedByTenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CardTransfer");

                    b.Navigation("DisposedByTenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DomainLayer.Entities.CardDisposalItem", b =>
                {
                    b.HasOne("DomainLayer.Entities.CardDisposal", "CardDisposal")
                        .WithMany("Items")
                        .HasForeignKey("CardDisposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.ProductItem", "ProductItem")
                        .WithMany()
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CardDisposal");

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("DomainLayer.Entities.CardTransfer", b =>
                {
                    b.HasOne("DomainLayer.Entities.BranchRequest", "BranchRequest")
                        .WithMany()
                        .HasForeignKey("BranchRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Entities.Tenant", "CreatedByTenant")
                        .WithMany()
                        .HasForeignKey("CreatedByTenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.CardTransfer", "ParentTransfer")
                        .WithMany()
                        .HasForeignKey("ParentTransferId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Entities.Branch", "SourceBranch")
                        .WithMany()
                        .HasForeignKey("SourceBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Branch", "TargetBranch")
                        .WithMany()
                        .HasForeignKey("TargetBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BranchRequest");

                    b.Navigation("CreatedByTenant");

                    b.Navigation("ParentTransfer");

                    b.Navigation("SourceBranch");

                    b.Navigation("TargetBranch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DomainLayer.Entities.CardTransferItem", b =>
                {
                    b.HasOne("DomainLayer.Entities.CardTransfer", "CardTransfer")
                        .WithMany("Items")
                        .HasForeignKey("CardTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.ProductItem", "ProductItem")
                        .WithMany()
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CardTransfer");

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("DomainLayer.Entities.CardTransferProduct", b =>
                {
                    b.HasOne("DomainLayer.Entities.CardTransfer", "CardTransfer")
                        .WithMany("Products")
                        .HasForeignKey("CardTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CardTransfer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DomainLayer.Entities.EvolisProductPrintConfiguration", b =>
                {
                    b.HasOne("DomainLayer.Entities.PrintImage", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.RibbonType", null)
                        .WithMany()
                        .HasForeignKey("RibbonTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DomainLayer.Entities.MaticaPrinterConfiguration", b =>
                {
                    b.HasOne("DomainLayer.Entities.Printer", "Printer")
                        .WithOne()
                        .HasForeignKey("DomainLayer.Entities.MaticaPrinterConfiguration", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("DomainLayer.Entities.MaticaProductPrintConfiguration", b =>
                {
                    b.HasOne("DomainLayer.Entities.PrintImage", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DomainLayer.Entities.PrintImage", b =>
                {
                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainLayer.Entities.Printer", b =>
                {
                    b.HasOne("DomainLayer.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DomainLayer.Entities.Product", b =>
                {
                    b.HasOne("DomainLayer.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainLayer.Entities.ProductItem", b =>
                {
                    b.HasOne("DomainLayer.Entities.Batch", "Batch")
                        .WithMany("CardsInBatch")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Branch");

                    b.Navigation("Product");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DomainLayer.Entities.Stock", b =>
                {
                    b.HasOne("DomainLayer.Entities.Branch", "SettledBranch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Product", "CardType")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Tenant", "Bank")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("CardType");

                    b.Navigation("SettledBranch");
                });

            modelBuilder.Entity("DomainLayer.Entities.Batch", b =>
                {
                    b.Navigation("CardsInBatch");
                });

            modelBuilder.Entity("DomainLayer.Entities.BranchRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DomainLayer.Entities.CardDisposal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DomainLayer.Entities.CardTransfer", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
