using DomainLayer.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DomainLayer.Entities
{
    /// <summary>
    /// A movement of cards from one branch to another (ERD §4.3, table
    /// <c>CardsTransferHistory</c>; API §4.10).
    /// <para>
    /// <b>Append-only.</b> Deliberately does <em>not</em> derive from <c>AuditableEntity</c>: per
    /// ERD §6.5 a transfer is immutable except for <see cref="TransactionStatus"/> and
    /// <see cref="StatusChangedAt"/>, is never soft-deleted, and has no restore endpoint. It
    /// therefore carries its own <see cref="CreatedAt"/> rather than inheriting the audit block,
    /// and it is not picked up by the <c>AuditSaveChangesInterceptor</c> — the service layer logs
    /// its non-CRUD actions explicitly through <c>IAuditLogger</c>.
    /// </para>
    /// <para>
    /// <b>Two ways a transfer is born.</b> A tenant user creates one directly — either standalone
    /// (<see cref="TransactionOrigin.UserCreated"/>, <see cref="BranchRequestId"/> null) or to
    /// fulfil a branch request (<see cref="TransactionOrigin.UserCreated"/>,
    /// <see cref="BranchRequestId"/> set, API §4.9) — or the system manufactures one to carry the
    /// unreceived remainder of a partial receipt back to its source
    /// (<see cref="TransactionOrigin.AutoGeneratedReturn"/>, <see cref="ParentTransferId"/> set,
    /// inheriting the parent's <see cref="BranchRequestId"/> per decision D-04).
    /// </para>
    /// <para>
    /// <b>Settlement.</b> There is no refuse endpoint. Every outcome flows through <c>receive</c>,
    /// which carries a disposition per product line: received, disposed, or (implicitly) returned.
    /// </para>
    /// </summary>
    public class CardTransfer
    {
        /// <summary>Primary key (BIGINT IDENTITY).</summary>
        [Key]
        public long Id { get; set; }

        /// <summary>Owning tenant id (FK → Tenants.Id).</summary>
        public long TenantId { get; set; }

        /// <summary>
        /// Navigation to the owning tenant. Present so that this and
        /// <see cref="CreatedByTenant"/> configure as two distinct relationships — EF Core
        /// identifies a relationship by its navigations, so two navigation-less
        /// <c>HasOne&lt;Tenant&gt;().WithMany()</c> calls would silently reconfigure the same one
        /// and leave the second foreign key unmapped.
        /// </summary>
        public Tenant Tenant { get; set; } = null!;

        /// <summary>
        /// The branch request this transfer fulfils (API §4.9), or <c>null</c> for a direct
        /// transfer created outside any request.
        /// <para>
        /// An auto-generated return transfer inherits its parent's <see cref="BranchRequestId"/>
        /// (decision D-04) so <c>GET /api/inventory/transactions?branchRequestId=</c> shows the
        /// full movement history a request caused, bounces included. Fulfilment credit is gated
        /// on direction, not on this id being set: only a transfer whose
        /// <see cref="TargetBranchId"/> equals the request's requesting branch credits
        /// <see cref="BranchRequestItem.ReceivedQuantity"/> — a return transfer heads away from
        /// the requesting branch, so it carries this id but never credits.
        /// </para>
        /// </summary>
        public long? BranchRequestId { get; set; }

        /// <summary>Navigation to the fulfilled branch request, or <c>null</c> for a direct transfer.</summary>
        public BranchRequest? BranchRequest { get; set; }

        /// <summary>UTC instant the transfer was created and dispatched.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Tenant that created the transfer (FK → Tenants.Id). Non-nullable, which is the
        /// structural reason a system admin cannot create a transfer (decision Q7) — an admin
        /// token carries no tenant id to put here.
        /// </summary>
        public long CreatedByTenantId { get; set; }

        /// <summary>Navigation to the creating tenant.</summary>
        public Tenant CreatedByTenant { get; set; } = null!;

        /// <summary>
        /// Username of the account that created this transfer (the "Maker").
        /// <para>
        /// <b>Why alongside <see cref="CreatedByTenantId"/>:</b> this system has one account per
        /// tenant (no separate users table), so <see cref="CreatedByTenantId"/> alone cannot
        /// distinguish "who" within a tenant acted. This column exists so the Maker's identity is
        /// always recorded even though, today, it will equal the tenant's single username - it is
        /// fine for the same account to be both Maker and Checker (Unknown-way Maker-Checker
        /// workflow, decision confirmed with the repo owner); what matters is that the identity is
        /// captured, not that two different identities be proven.
        /// </para>
        /// <para>
        /// <b>Schema note:</b> not in the original ERD; added for the Unknown-way Maker-Checker
        /// workflow (approved). Flagged for DBA review.
        /// </para>
        /// </summary>
        public string CreatedByUsername { get; set; } = string.Empty;

        /// <summary>
        /// Username of the account that settled this transfer (the "Checker") - the caller of
        /// <c>receive</c> or <c>dispose</c>, whichever ran <see cref="Enums.TransactionStatus"/>'s
        /// terminal transition. <c>null</c> while <see cref="TransactionStatus"/> is still
        /// <see cref="Enums.TransactionStatus.InProgress"/>. See <see cref="CreatedByUsername"/>
        /// for why this is a username rather than a per-user id.
        /// <para>
        /// <b>Schema note:</b> not in the original ERD; added for the Unknown-way Maker-Checker
        /// workflow (approved). Flagged for DBA review.
        /// </para>
        /// </summary>
        public string? CheckedByUsername { get; set; }

        /// <summary>Branch the cards left (FK → Branches.Id).</summary>
        public long SourceBranchId { get; set; }

        /// <summary>Navigation to the source branch.</summary>
        public Branch SourceBranch { get; set; } = null!;

        /// <summary>Branch the cards are headed to (FK → Branches.Id). Never equal to the source.</summary>
        public long TargetBranchId { get; set; }

        /// <summary>Navigation to the target branch.</summary>
        public Branch TargetBranch { get; set; } = null!;

        /// <summary>Lifecycle state. Only <see cref="Enums.TransactionStatus.InProgress"/> is non-terminal.</summary>
        /// <remarks>
        /// The property intentionally shares its name with its type, matching the ERD §4.3 column
        /// name. The initializer is fully qualified so the compiler is never asked to disambiguate.
        /// </remarks>
        public TransactionStatus TransactionStatus { get; set; } = Enums.TransactionStatus.InProgress;

        /// <summary>UTC instant the status last changed, or <c>null</c> while still in progress.</summary>
        public DateTime? StatusChangedAt { get; set; }

        /// <summary>
        /// Free-text note captured at settlement — the disposal reason, or a receiving remark.
        /// <para>
        /// <b>Schema note:</b> not in ERD §4.3; added with decision Q8 (approved). ERD §4.1 already
        /// models the equivalent on branch requests. Flagged for DBA review.
        /// </para>
        /// </summary>
        public string? ActionNotes { get; set; }

        /// <summary>Whether a person raised this transfer or the system manufactured it.</summary>
        public TransactionOrigin Origin { get; set; } = TransactionOrigin.UserCreated;

        /// <summary>
        /// The transfer whose partial receipt produced this one (self-FK → CardsTransferHistory.Id),
        /// or <c>null</c> for an ordinary transfer.
        /// <para>
        /// <b>Correction from the original T1 note on this property:</b> chains are <em>not</em>
        /// capped at one level. A return transfer is settled through the exact same code path as
        /// any other transfer — receive with a per-line disposition of received, disposed, or
        /// returned — and a partial receipt on a return spawns a further return exactly as a
        /// partial receipt on an ordinary transfer does. <c>Parent.Parent</c> can be non-null.
        /// Nothing about the entity assumes a bound on chain depth; it is a plain linked list.
        /// </para>
        /// </summary>
        public long? ParentTransferId { get; set; }

        /// <summary>Navigation to the parent transfer, or <c>null</c>.</summary>
        public CardTransfer? ParentTransfer { get; set; }

        /// <summary>
        /// Optimistic-concurrency token guarding the status flip.
        /// <para>
        /// <b>Schema note:</b> not in ERD §4.3; added with decision Q8 (approved). Without it two
        /// concurrent receive calls can both read <see cref="Enums.TransactionStatus.InProgress"/>
        /// and both move stock — a status re-read inside the transaction narrows that window but
        /// does not close it.
        /// </para>
        /// </summary>
        [Timestamp]
        public byte[] RowVersion { get; set; } = null!;

        /// <summary>Product lines carried by this transfer. At least one always exists.</summary>
        public List<CardTransferProduct> Products { get; set; } = new();

        /// <summary>
        /// Individually tracked cards. Populated only for Known-way product lines; an Unknown-way
        /// transfer carries quantities and no item rows at all.
        /// </summary>
        public List<CardTransferItem> Items { get; set; } = new();
    }
}
