using DomainLayer.Common;

namespace DomainLayer.Entities
{
    /// <summary>
    /// Matica printing parameters for a product (ERD §7.2, table
    /// <c>MaticaProductPrintConfigurations</c>; Printing Module decisions Q-02/Q-03/Q-04). Exactly
    /// one row per product among non-deleted rows — decision Q-02 dropped the ERD's per-face
    /// cardinality, so there is deliberately no <c>PrintedFace</c> column here (decision Q-04).
    /// Field set is <see cref="Cpi"/>, <see cref="FontSize"/>, <see cref="OffsetX"/>,
    /// <see cref="OffsetY"/>, and <see cref="ImageId"/> per decision Q-03 — no separate
    /// <c>Font</c>/<c>FontFamily</c> field.
    /// <para>
    /// Lifecycle follows the owning <see cref="Product"/> as a single aggregate (module
    /// requirement §2): created alongside the product, updated alongside it, soft-deleted and
    /// restored alongside it. The one exception is a printer-family switch (decision Q-08): this
    /// row is hard-deleted — never soft-deleted — in the same transaction that creates the
    /// replacement <see cref="EvolisProductPrintConfiguration"/> row.
    /// </para>
    /// </summary>
    public sealed class MaticaProductPrintConfiguration : AuditableEntity
    {
        /// <summary>Primary key (BIGINT IDENTITY).</summary>
        public long Id { get; set; }

        /// <summary>
        /// Owning tenant id (FK → Tenants.Id). Denormalized from <see cref="Product"/>, matching
        /// this codebase's existing pattern for child rows of a tenant-owned aggregate (e.g.
        /// <see cref="BranchRequestItem.TenantId"/>), so tenant-scoped queries need no join.
        /// </summary>
        public long TenantId { get; set; }

        /// <summary>The product this configuration belongs to (FK → Products.Id). Unique per tenant among non-deleted rows.</summary>
        public long ProductId { get; set; }

        /// <summary>
        /// Navigation to the owning product. Added in P6: when a product and its Matica
        /// configuration are created in the same transaction (module requirement §4's
        /// single-aggregate create flow, wired up in a later phase), <see cref="ProductId"/> does
        /// not exist yet — it's generated by the product's own insert within that same
        /// <c>SaveChanges</c> call. Setting <see cref="Product"/> (not <see cref="ProductId"/>
        /// directly) lets EF Core fix up the foreign key once that id exists, the same mechanism
        /// <c>MaticaPrinterConfiguration.Printer</c> already relies on (P5). Once the product
        /// already has a real id (every other write path), setting either works identically.
        /// </summary>
        public Product Product { get; set; } = null!;

        /// <summary>Characters-per-inch for the printed text.</summary>
        public int Cpi { get; set; }

        /// <summary>Font size in points.</summary>
        public int FontSize { get; set; }

        /// <summary>Horizontal print offset.</summary>
        public int OffsetX { get; set; }

        /// <summary>Vertical print offset.</summary>
        public int OffsetY { get; set; }

        /// <summary>
        /// The print image for this configuration (FK → PrintImages.Id). Null until an image has
        /// been uploaded and attached. Replaces the earlier bare <c>ImagePath</c> string (single
        /// source of truth: <see cref="PrintImage"/> owns the image's metadata and physical
        /// location; this table only references it by id).
        /// </summary>
        public long? ImageId { get; set; }
    }
}
